version: "3.8"

services:
  mongodb:
    image: mongo:6.0.5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - MONGO_DATA:/data/db

volumes:
  MONGO_DATA: {}
